exports.initialAccountData = [{
  name: "现金",
  description: "",
  balance: 0,
  inTotal: 0,
  outTotal: 0,
  iconPath: "/static/account/xj.png",
  bgColor: "background: linear-gradient(to right, #F56C6C, #F48C8C);",
}, {
  name: "微信钱包",
  description: "",
  balance: 0,
  inTotal: 0,
  outTotal: 0,
  iconPath: "/static/account/wx.png",
  bgColor: "background: linear-gradient(to right, #67C23A, #7BD051);",
}, {
  name: "支付宝",
  description: "",
  balance: 0,
  inTotal: 0,
  outTotal: 0,
  iconPath: "/static/account/zfb.png",
  bgColor: "background: linear-gradient(to right, #409EFF, #5BACFF);",
}, {
  name: "银行卡",
  description: "尾号 xxxx",
  balance: 0,
  inTotal: 0,
  outTotal: 0,
  iconPath: "/static/account/yhk.png",
  bgColor: "background: linear-gradient(to right, #E6A23C, #FBBF65);",
}]
